version: "3"
services:
  app:
    build: .
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py makemigrations &&
             python3 manage.py migrate"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  celery-beat:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./:/app
    command: celery -A scraping_task beat --loglevel=INFO
    depends_on:
      - redis
      - postgres
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=Europe/Kiev

  celery-worker:
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./:/app
    depends_on:
      - redis
      - postgres
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=Europe/Kiev
    command: celery -A scraping_task worker --loglevel=INFO

  redis:
    restart: unless-stopped
    image: redis:latest
    environment:
      - TZ=Europe/Kiev

  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
