# Generated by Django 4.2.6 on 2023-10-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('price_usd', models.IntegerField()),
                ('odometer', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('images_count', models.IntegerField()),
                ('car_number', models.CharField(max_length=255, null=True)),
                ('car_vin', models.CharField(max_length=255)),
                ('datetime_found', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
