# Generated by Django 4.2.6 on 2023-10-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_db', '0002_alter_car_car_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
